services:
  - type: web
    name: zap-workflow
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    healthCheckPath: /login
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
